### ISSUE TITLE
V11 Compatibility Issues?

### ISSUE THREAD

**Issue by RinVindor** [SvenWerlen/fvtt-data-toolbox#36] opened 2023-08-03 03:26 UTC
Not entirely sure but I'm having issues with importing as of V11. The import works on the first item within the import but fails to go further and mentions Uncaught (in promise) Error: TypeError: Cannot read properties of undefined (reading 'update') at GenerateCompendiumDialog._generate (data-toolbox.js:201:15)

![image](https://github.com/SvenWerlen/fvtt-data-toolbox/assets/12647469/ad535af3-1f66-41c4-8a8b-68bed6659795)

Template
`{
  "name": "{{name}}",
  "type": "{{type}}",
  "img": "systems/mutants-and-masterminds-3e/assets/icons/talent.svg",
  "system": {
    "description": "{{info}} - {{description}}",
    "equipement": "{{equipement}}",
    "rang": "{{rang}}",
    "accessibility": {
      "font": "Kalam"
    }
  }
}`

.csv file
![image](https://github.com/SvenWerlen/fvtt-data-toolbox/assets/12647469/18c0f955-21ef-47dc-ac5e-cb3cae420e78)

**Comment by SvenWerlen** [comment] 2024-02-10 20:55
It took me too long to check this. Sorry for that.

I'm not able to reproduce it.
I close it but if it is still an issue, feel free to reopen it. 
_(please share the template & data such I can reproduce it)_

**Closed as completed by SvenWerlen** 2024-02-10 20:55 UTC
